on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish /home/runner/work/BCSS/BCSS/BCSSViewer.Wasm/BCSSViewer.Wasm.csproj -c Release -f net7.0 --output ./Release
    - name: index.html base tag
      run: sed -i 's/<base href="\/" \/>/<base href="\/bcss\/" \/>/g' /home/runner/work/BCSS/BCSS/BCSS/bin/Release/net7.0/publish/wwwroot/index.html
    - name: 404.html
      run: sed -i 's/\/?p=\//\/bcss\/?p=\//g' /home/runner/work/BCSS/BCSS/BCSS/bin/Release/net7.0/publish/wwwroot/404.html
    
    - name: 📂 Sync files
      if: ${{ github.repository_owner == 'CodeBeamOrg' }}
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./Release/wwwroot/
        server-dir: ./bcss/
